# Generated by Django 4.2.11 on 2024-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_punlished_at_job_published_at_alter_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
