# Generated by Django 4.2.11 on 2024-12-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
    ]
