# Generated by Django 4.2.11 on 2024-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_remove_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
